name: enough_icalendar
description: iCalendar library to parse, generate and respond to iCal / ics
  invites. Fully compliant with RFC 5545 (iCalendar) and RFC 5546 (iTIP).
version: 0.14.0
homepage: https://github.com/Enough-Software/enough_icalendar

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  intl: ^0.18.0

dev_dependencies:
  dart_code_metrics: ^5.6.0
  lints: ^3.0.0
  test: ^1.20.2
