name: enough_icalendar
description: iCalendar library to parse, generate and respond to iCal / ics
  invites. Fully compliant with RFC 5545 (iCalendar) and RFC 5546 (iTIP).
version: 0.17.0
homepage: https://github.com/Enough-Software/enough_icalendar
topics: 
 - icalendar
 - ics
 - ical
 - rfc5545
 - rfc5546
 
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  intl: any # be compatible with any Flutter version

dev_dependencies:
  lints: ^6.0.0
  test: ^1.20.2
